### ISSUE TITLE
CSP Constraint Generation

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon#509]
Currently we only generate CSP constraints such that all given Free/Bound combinations of the user are generated.
Sometimes this might be bad as we've seen in the consistency check case.
In the future it would make more sense to generate a function that can handle all Free/Bound permutations and throws an UnsupportedOperationException if the distinct permutation has not yet been implemented.

**Comment by anthonyanjorin** [comment]
I don't understand the suggestion.  What is currently the problem and how should it be improved?

**Comment by RolandKluge** [comment]
@anthonyanjorin @Arikae  Is this issue still valid?

**Comment by anthonyanjorin** [comment]
Handling all possible F/B permutations is not a good idea as suddenly all possible search plans are valid.
Consistency check generation is simply not possible for some TGGs due to missing operations for certain constraints.  That can only be fixed by the user extending the constraints or changing the TGG.
