### ISSUE TITLE
[Democles] For some reason search plan generation takes for ever for this actually quite small and simple looking TGG

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#513]
It takes forever (more than an hour so I gave up) to generate code for the attached eap.
In the debugger it appears to be spending all the time in the search plan generation for the TGG.

No idea why these patterns are particularly nasty...

https://dl.dropboxusercontent.com/u/53995103/searchplanproblem.zip

**Comment by gervarro** [comment]
Hi Tony,
I would guess that some rules contain not connected (unconnected) patterns, which are large and for which no search plan exists due to their unconnected nature. (I know that this issue should be fixed in general.)

Could you please help me/us identifying the problematic location (pattern / TGG rule) with the following method?
- Start an Eclipse in debug mode
- Try to generate code with the standard process
- Click suspend, and set a breakpoint at the search plan generation, and then resume the code generation until the breakpoint is hit.
- Please search for a method in the stack trace (somewhere at the bottom), which has an EOperation as a parameter. The container (EClass) of the EOperation parameter shows, which rule is problematic.

Bests, Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

you're absolutely right!  It's a pattern with no search plan (as a node is in the air).

@mabilov The problem is in the rule ParallelGateway2ParallelStepSeq.  The ov "flow" is not connected to the rest of the context for the isApplicable_FWD method (so when searching for the entire context in the forward direction).

A picture of the problematic pattern is given here:  https://dl.dropboxusercontent.com/u/53995103/Pattern_253367944.svg

@gervarro What is the plan here?  Prior validation to report such cases as errors before searching for a search plan that cannot exist?  Anyway if you get to optimising this then you could use this as an example :)

Thanks!
Tony

**Comment by mabilov** [comment]
Thank you, I found the problematic node and connected it to another node, so it won't just in the air.

**Comment by RolandKluge** [comment]
This issue was moved to eMoflon/emoflon-tool#21
