### ISSUE TITLE
[SDM] Use activity node name as method name for patterns

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#515]
Would it be possible to use the name of activity nodes as method name instead of the generated method names when generating code for SDMs?

Consider the following snippet:
// EliminateMatchesOfNACs		      
AlgoImpl.pattern_ICMT2015IncrementalKTCAlgorithm_0_6_expressionBB(this, outdatedLink);
// ActivateLink
AlgoImpl.pattern_ICMT2015IncrementalKTCAlgorithm_0_7_expressionFBB(this, outdatedLink);
// InactivateLink
AlgoImpl.pattern_ICMT2015IncrementalKTCAlgorithm_0_8_expressionFBB(this, outdatedLink);

This would look much nicer:	      
    AlgoImpl.pattern_EliminateMatchesOfNACs_0_6_expressionBB(this, outdatedLink);
    AlgoImpl.pattern_ActivateLink_0_7_expressionFBB(this, outdatedLink);
    AlgoImpl.pattern_InactivateLink_0_8_expressionFBB(this, outdatedLink);

Of course, not all names of activity nodes make valid identifiers in a method.
We could
(1) Check the name using a regex
(2) Replace all invalid characters, e.g. with '?' or '_' (for whitespaces)

**Comment by anthonyanjorin** [comment]
Additional problems:

(3) some anodes do not even have names ("")
(4) some are long comments

Instead of fixing I would suggest a validation rule in EA to flag "problematic" names, and then just a simple check when generating code if the name is valid, if not then default as now.  

Not sure how difficult this is though with the templates, but yes Roland is right concerning readability.

**Comment by RolandKluge** [comment]
Right, I forgot to mention that we should resort to the default name in case of problems.

**Comment by gervarro** [comment]
This seems to be a recurring topic. ;-) The answer is: yes and no.
It was a design decision to separate patterns completely from the control flow in order to support the invocation of a pattern from several locations in the future. In such a case, a pattern does not even have a well-identifiable location in the SDM specification. I know that the current implementation generates at most 5 new patterns for each activity node, and in this sense, the corresponding pattern is unambiguously identifiable in the SDM specification (i.e., each pattern stems from a corresponding activity node). It is not an extremely large effort to perform the renaming in the validation process (1 or 2 locations), but such a modification would block another feature, and this issue does not have a top priority on my list. (If it is really that annoying, and we do not care for the other feature, then you can solve it in 2 minutes (at least the modification of the validation process).)
Anyway, your suggestions still do not solve/consider the problem of unambiguously identifying the method (i.e., the meaning of the first number), in which a pattern occurs.

**Comment by RolandKluge** [comment]
We should discuss that prior to the next hackerdays.

Actually, it would be a convenience feature, which should never block any more important features!

**Comment by RolandKluge** [comment]
We agreed at our eMoflon planning meeting that it would make sense to implement this feature.

The place where the adjustment would take place is the following injection: ScopeValidation.impl.PatternInvocationBuilderImpl.calculatePatternName(CFNode)

**Comment by RolandKluge** [comment]
Solved. I implemented a really conservative strategy that only allows blanks (get replaced with '-'), letters, digits, and underscores.
