### ISSUE TITLE
Validation: Report on validation crash during Clean and Build

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#584]
If the validation crashes ("Internal exception occurred") during Clean and Build, the user receives no feedback about this problem. Only when running the validation manually, an error dialog is shown.

Edit: Here is the problematic EAP file: https://github.com/eMoflon/emoflon/raw/master/issuefiles/issue584__validation_crashes_for_this_eap_file.zip

**Comment by RolandKluge** [comment]
One problem in the specification was that no search plan for the third activity node exists - still the validation kept on crashing.

I found the following solution:
![hacked_solution_for_crashing_validation_issue584](https://cloud.githubusercontent.com/assets/4731838/10247086/b5575dfc-6916-11e5-83b2-6273dcb1e028.png)

I suspect that this is the famous loop-detection bug/problem.

**Comment by gervarro** [comment]
I do not really understand the situation. I updated the Eclipse-based error reporter (producing markers) to handle all kinds of problems that come along with a status. (This could have been fixed by Géza as well, as he wrote this code snippet.)

Error reporting in an error dialog is a matter of debate. Validation is always invoked explicitly from the user interface, consequently reporting errors in a dialog is OK. Code generation, which is based on a builder, should run in the background, which means reporting errors in a pop-up dialog is not necessarily the best idea. (Imagine if the Java compiler would report errors and warnings like this for each file.)

If I understand correctly, the above figure describes a correct SDM specification, however, the MetamodelBuilder did not even produce the 2 metamodels (ecore files) on my computer, when I executed on the exported Moca tree.

**Comment by RolandKluge** [comment]
The problem for me was that the validation crashed with a runtime exception but I did not find any notification about that in the console.

I agree with you that we do not want to have any dialogs pop up in a “non-interactive” process.

I would prefer to see a log message (if the validation crashes).  If it does not crash, then the log messages tell the user that the validation report is being sent to EA etc.

I could reproduce the runtime exception with eMoflon 2.2.1 and with a not-up-to-date version of the dev. workspace. This may be the reason why you could not reproduce this behavior.

As I posted before, the problem may be related to the loop detection – for me, the issue could be fixed with an empty activity node.

Best,
Roland

Von: gervarro [mailto:notifications@github.com]
Gesendet: Freitag, 2. Oktober 2015 21:25
An: eMoflon/emoflon <emoflon@noreply.github.com>
Cc: Roland Kluge <Roland.Kluge@es.tu-darmstadt.de>
Betreff: Re: [emoflon] Validation: Report on validation crash during Clean and Build (#584)


I do not really understand the situation. I updated the Eclipse-based error reporter (producing markers) to handle all kinds of problems that come along with a status. (This could have been fixed by Géza as well, as he wrote this code snippet.)

Error reporting in an error dialog is a matter of debate. Validation is always invoked explicitly from the user interface, consequently reporting errors in a dialog is OK. Code generation, which is based on a builder, should run in the background, which means reporting errors in a pop-up dialog is not necessarily the best idea. (Imagine if the Java compiler would report errors and warnings like this for each file.)

If I understand correctly, the above figure describes a correct SDM specification, however, the MetamodelBuilder did not even produce the 2 metamodels (ecore files) on my computer, when I executed on the exported Moca tree.

**Comment by RolandKluge** [comment]
I solved this temporarily by returning an error status if the validation crashes.
