### ISSUE TITLE
[IDE] Eclipse Mars isn't recognizing the eMoflon Update Site

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon#592]
If you try to install the beta of eMoflon from the update Site 
![screenshot 2015-10-09 11 22 34](https://cloud.githubusercontent.com/assets/9741282/10390337/3fc0af64-6e78-11e5-8163-e791214a06fb.png)
If you use Luna to look the update site or an older version of eMoflon (I testet it with 20150828 from Dropbox deployment) it's working fine.

**Comment by RolandKluge** [comment]
I do not quite understand the problem: Is you Eclipse unable to retrieve the current version (2.2.1)? What happens if you untick "Hide items that are already installed"?

You may also try the "emoflon.org" version of the link:
http://www.emoflon.org/fileadmin/download/moflon-ide/eclipse-plugin/beta/update-site2/

**Comment by SchroedingersCatIsUndead** [comment]
ok, switching the link to emoflon.org solved the problem. But the website link to http://www.moflon.org/fileadmin/download/moflon-ide/eclipse-plugin/beta/update-site2/ which have the problem from above so the website should be updated to the right link

**Comment by RolandKluge** [comment]
Thank you for discovering this problem. Seems to be a problem of Eclipse in conjunction with HTTP redirects.

I have updated the link on http://www.emoflon.org/emoflon/installation/
