### ISSUE TITLE
Update "Install Workspace/Developer workspaces" menu

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#649]
First of all rename to "Developer *W*orkspaces"

Then remove the "should I delete all workspaces?" dialogue.

I've tested all our new "dev" PSFs so let's switch as follows:
* Get project with all PSFs
* Install Handbook (Latex)
* All Developer and Test Workspaces
* ... list of all our new PSF files ...

Is anything else really necessary?  I find the (current PSF, installed PSF) confusing and unnecessary as we have the PSF selection dialogue.

Finally delete any PSFs that we no longer need.  We could also structure the project better (currently there is only the sub folder /dev).

@RolandKluge or @erhanleblebici Please delegate to a suitable Hiwi.

**Comment by anthonyanjorin** [comment]
We do have a bug to fix, concerning genModels that are required but not in the workspace.  It seems the code generator expects genmodel to always be in the workspace...   Have to look into this first (affects Core + SDM due to the strange dependency of mocatomoflon on TGG projects)!

**Comment by anthonyanjorin** [comment]
We do have a bug and here are my findings:

* In both deployed and runtime (spawned from a complete dev workspace) state, I get the following error:  
´´´
The package 'platform:/plugin/MocaTree/model/MocaTree.ecore#/' has the same namespace URI 'platform:/plugin/MocaTree/model/MocaTree.ecore' as package 'platform:/plugin/MocaTree/model/MocaTree.ecore#/'
´´´
This is also reported for SDMLanguage related packages.

I tried commenting out the genmodel validation call in MonitoredGenModelBuilder.java and everything worked.  That means that it is the genmodel validation that reports this problem and it seems to be (at least in this case) a bit paranoid.

I do not understand what the problem is and why it only occurs for this project and for these dependencies :(

**Comment by anthonyanjorin** [comment]
Ok I think I can guess at the problem:

[Core + SDM] depends on [TGG] because mocatomoflon (unfortunately) also handles TGG projects.

Now as [TGG] is not in the workspace, these dependencies are resolved automatically using the installed plugin.  That works fine, but the dependencies of [TGG], namely [SDM] and [MocaTree], are also loaded.

This causes a clash, as SDM and MocaTree are already in the workspace BUT are not resolved as the dependencies of [TGG].

Hope that was understandable :)

I suggest we add the four projects in [TGG] for the time being to [Core + SDM].  This problem should go away if we are able to establish a textual concrete syntax for TGGs as planned.  In that case we could just delete the TGG-specific parts of mocatomoflon and the problem would go away.

What do you think @gervarro  @erhanleblebici @RolandKluge?

**Comment by gervarro** [comment]
> I've tested all our new "dev" PSFs so let's switch as follows:
>
>    Get project with all PSFs
>    Install Handbook (Latex)
>    All Developer and Test Workspaces
>    ... list of all our new PSF files ...
>
> Is anything else really necessary?

If we are already in a phase, when we update the Eclipse UI of eMoflon, I would turn all UI blocking operations (e.g., Install dev workspace) into non-blocking ones. (I find UI blocking operations extremely disturbing as a user.) I guess that @RolandKluge already converted some UI blocking operations, but if I remember correctly, the workspace installation still blocks the Eclipse UI.

> [Core + SDM] depends on [TGG] because mocatomoflon (unfortunately) also handles TGG projects.
>
> Now as [TGG] is not in the workspace, these dependencies are resolved automatically using the installed plugin. That works fine, but the dependencies of [TGG], namely [SDM] and [MocaTree], are also loaded. This causes a clash, as SDM and MocaTree are already in the workspace BUT are not resolved as the dependencies of [TGG].
>
> Hope that was understandable :)

@anthonyanjorin: You are right. That is exactly the problem. The fully automated project dependency handling mechanism, which is not yet integrated into eMoflon, would solve the problem. I hope I will have time for that this summer.

> I suggest we add the four projects in [TGG] for the time being to [Core + SDM].

That is OK as a temporary solution.

> This problem should go away if we are able to establish a textual concrete syntax for TGGs as planned. 

You are right.

> In that case we could just delete the TGG-specific parts of mocatomoflon and the problem would go away.

I would be careful with the deletion. The tool chain starting from a(n existing) graphical TGG specification (with EA as frontend) should also work with the new setup. What are our plans in this regard?

@erhanleblebici @anthonyanjorin: I would initiate another discussion regarding the transformation from a TGG specification (.tgg.xmi) to the corresponding metamodel (.tgg.ecore). While designing the incremental PM based TGG engine, we already raised the issue of handling "protocol" objects. I think that the most efficient solution in the new setup would be to generate (at compile time) and use (at runtime) compiled/tailored protocol objects (instead of generic protocol objects), which would require adjusting the transformation to prepare the tailored protocol classes as subclasses of AbstractRule or AbstractCorrespondence. @erhanleblebici: I will explain what I mean exactly, when I am in Darmstadt again.

**Comment by anthonyanjorin** [comment]
Although it would be great to maintain both a visual and a concrete textual syntax, I doubt if we have enough resources to do so.  A realistic plan, therefore, would be to have a release with both where the conversion works, but then only support one syntax in future versions.  This is especially the case for future changes, new features, etc.

Concerning the new incr. PM-based tgg engine, our current plan (for numerous reasons) is to establish this as a completely separate module, which will have nothing to do with the current tgg implementation.

**Comment by RolandKluge** [comment]
Modularization can be considered done so far. The installation menu has been updated.
