### ISSUE TITLE
Serious slow down of code generation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon#734]
Right now we have a sudden serious slowdown of the code generation process.

It's not that easy to figure out what exactly is causing this, but I suspect it has something to do with the very very many validation messages now produced by democles:

´´´
!SUBENTRY 2 org.moflon.compiler.sdm.democles 2 0 2016-05-12 23:33:39.320
!MESSAGE Incompatible type in expression
´´´

Could this be the case?  

FYI @RolandKluge

**Comment by anthonyanjorin** [comment]
@erhanleblebici  is going to do some profiling here so we know more precisely what is causing the slow down.  If it really is because of the "errors" in SDMs generated from TGGs then we'll fix this ASAP.

**Comment by gervarro** [comment]
> Right now we have a sudden serious slowdown of the code generation process.
>
> It's not that easy to figure out what exactly is causing this, but I suspect it has something to do with the very very many validation messages now produced by democles:

I haven't changed the code generation process at all for more than a year, so I would guess that it has some other reasons, if you did not experience the same problem before. Did you modify the TGG compilation process recently? Or have you installed a new EMF version? ;-)

@erhanleblebici and I did some profiling a couple of months ago, because the "TGG compilation and code generation process" was extreme slow. The most time was spent on some new and strange activities in EMF itself. The TGG compilation process was on the second place, which is understandable if many new methods are created. The most surprising thing was that even the StringTemplate based code generation was slower than the SDM validation process. SDM validation takes extreme long if there are no valid search plans, however embedding Fred's reachability analysis (which has not been carried out yet) would cause a significant speed up even in this case.

**Comment by anthonyanjorin** [comment]
Damn -- ok then we really have to do some profiling here :)

**Comment by RolandKluge** [comment]
Is this issue still relevant?

**Comment by RolandKluge** [comment]
Seems to be obsolete.
