### ISSUE TITLE
TGG projects are not auto-built in all test workspaces

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#795]
For some strange reason, none of the TGG projects in the test workspaces (Zoo1, Zoo0, TGG0, TGG1, Misc) is built correctly by the new built process during the automatic workspace installation procedure (*WorkspaceInstaller*). However, all of them build properly during a subsequent full built (*Hammer*).

Could you check this please using (e.g.,) the internal release 2.17.0?

**Comment by gervarro** [comment]
I think that it might be due to a plugin version clash/inconsistency in your Eclipse installation/workspace instance. I installed 3 of the above-mentioned 5 test workspaces fully automatically and without any problems (all tests are green) on a clean workspace.

The only thing that is really strange that a full build seems to be carried out before running the test suite, although all projects should be in a consistent state, consequently a build would not be  necessary.

**Comment by RolandKluge** [comment]
Confirmed -> obsolete.
